name: Pylint

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.2
    - name: Install Python
      uses: actions/setup-python@v4.6.0
      with:
          python-version: 3.10.8
    - name: Upgrade pip
      run: |
        pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint ${{ github.workspace }}/2.OOP/Tasks/4/*.py')
