name: Python Pylint

on: 
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up Python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.10.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run pylint
      run: |
        pylint 2.OOP/Tasks/4/4_2.py
